version: '3'
   
services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: password

  website:
    tty: true
    stdin_open: true
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/open_erp'
    environment:
      DB_USER: postgres
      DB_NAME: open_erp
      DB_PASSWORD: password
      DB_HOST: postgres
   
volumes:
  postgres:
